### ISSUE TITLE
ZeroDivisionError when applying gradient translation

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/picosvg#129]
the infamous baseball emoji (U+26BE) produces a ZeroDivisionError when passed through the latest picosvg (following #128)

```
$ picosvg ../color-fonts/font-srcs/noto-emoji/svg/emoji_u26be.svg
Traceback (most recent call last):
  File "/Users/clupo/Github/nanoemoji/.venv/bin/picosvg", line 33, in <module>
    sys.exit(load_entry_point('picosvg', 'console_scripts', 'picosvg')())
  File "/Users/clupo/Github/picosvg/src/picosvg/picosvg.py", line 39, in main
    svg = SVG.parse(input_file).topicosvg()
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 822, in topicosvg
    svg.topicosvg(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 841, in topicosvg
    self._apply_gradient_translation(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 761, in _apply_gradient_translation
    y_prime = (r2 - r1 * b / a) / (d - b * c / a)
ZeroDivisionError: float division by zero
```

Investigating

**Comment by anthrotype** [comment]
it contains a radialGradient with a 90 degree rotation, hence Affine2D's `a` and `d` are 0

```
    <radialGradient id="f" cx="-779.79" cy="3150" r="58.471" gradientTransform="matrix(0 1 -1 0 3082.5 1129.5)" gradientUnits="userSpaceOnUse">
```

**Comment by anthrotype** [comment]
I can't figure out the math, so I propose for now we simply skip applying translation for these

```diff
diff --git a/src/picosvg/svg.py b/src/picosvg/svg.py
index b82838a..247ea93 100644
--- a/src/picosvg/svg.py
+++ b/src/picosvg/svg.py
@@ -734,7 +734,7 @@ class SVG:
             )
             affine = gradient.gradientTransform
             a, b, c, d, dx, dy = affine
-            if (dx, dy) == (0, 0):
+            if a == 0 or (dx, dy) == (0, 0):
                 continue
             affine_prime = affine._replace(e=0, f=0)

```
