### ISSUE TITLE
Not all emojis pass picosvg?

### ISSUE THREAD

**Issue by tomasdev** [googlefonts/picosvg#170]
Running picosvg on https://github.com/googlefonts/noto-emoji/blob/master/svg/emoji_u1f54d.svg throws:

```
emoji_u1f54d.svg
Traceback (most recent call last):
  File "sheet.py", line 20, in <module>
    psvg = svg.topicosvg()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/picosvg/svg.py", line 945, in topicosvg
    svg.topicosvg(inplace=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/picosvg/svg.py", line 972, in topicosvg
    "Unable to convert to picosvg: " + ",".join(nano_violations)
ValueError: Unable to convert to picosvg: BadElement: /svg[0]/pattern[1],BadElement: /svg[0]/pattern[49],BadElement: /svg[0]/pattern[51],BadElement: /svg[0]/pattern[53],BadElement: /svg[0]/pattern[83],BadElement: /svg[0]/pattern[85],BadElement: /svg[0]/pattern[87],BadElement: /svg[0]/pattern[90],BadElement: /svg[0]/pattern[91],BadElement: /svg[0]/pattern[95]
```

**Comment by tomasdev** [comment]
Closed in favor of https://github.com/googlefonts/color-fonts/issues/10
