### ISSUE TITLE
Error when path is separated by spaces

### ISSUE THREAD

**Issue by yisibl** [googlefonts/picosvg#171]
Original svg

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 750 1125">
    <path d="M448.6,997.7c.2,5.6,16.6,9.4,36.5,8.4s35.8-6.2,35.5-11.8a1.7,1.7,0,0,0-.1-.7c-1.5-5.2-17.3-8.6-36.4-7.7s-34.4,5.8-35.5,11.1Z" fill="green" />
</svg>
```

After [svgo](https://github.com/svg/svgo) compression, the spaces are removed, and an error will be reported:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 750 1125">
    <path d="M448.6 997.7c.2 5.6 16.6 9.4 36.5 8.4s35.8-6.2 35.5-11.8a1.7 1.7 0 00-.1-.7c-1.5-5.2-17.3-8.6-36.4-7.7s-34.4 5.8-35.5 11.1z" fill="green" />
</svg>
```

```shell
nanoemoji --color_format=glyf_colr_0 $(find ../noto-emoji/svg -name 'emoji_u6a.svg')
Wrote  /Users/yisi/works/nanoemoji/build/config.toml
Generating build.ninja
ninja -C /Users/yisi/works/nanoemoji/build
ninja: Entering directory `/Users/yisi/works/nanoemoji/build'
[2/4] picosvg  --clip_to_viewbox ../../noto-emoji/svg/emoji_u6a.svg > picosvg/regular/emoji_u6a.svg
FAILED: picosvg/regular/emoji_u6a.svg
picosvg  --clip_to_viewbox ../../noto-emoji/svg/emoji_u6a.svg > picosvg/regular/emoji_u6a.svg
Traceback (most recent call last):
  File "/Users/yisi/works/nanoemoji/tutorial-env/bin/picosvg", line 8, in <module>
    sys.exit(main())
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/picosvg/picosvg.py", line 66, in main
    app.run(_run, argv=argv)
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/picosvg/picosvg.py", line 47, in _run
    svg = SVG.parse(input_file).topicosvg()
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/picosvg/svg.py", line 945, in topicosvg
    svg.topicosvg(inplace=True)
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/picosvg/svg.py", line 961, in topicosvg
    self.remove_unpainted_shapes(inplace=True)
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/picosvg/svg.py", line 725, in remove_unpainted_shapes
    if not shape.might_paint():
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/picosvg/svg_types.py", line 199, in might_paint
    if all(c[0].upper() == "M" for c in self.as_cmd_seq()):
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/picosvg/svg_types.py", line 231, in as_cmd_seq
    self.as_path()
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/picosvg/svg_types.py", line 514, in explicit_lines
    target.walk(_explicit_lines_callback)
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/picosvg/svg_types.py", line 432, in walk
    for idx, (cmd, args) in enumerate(self):
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/picosvg/svg_path_iter.py", line 71, in parse_svg_path
    args_per_cmd = svg_meta.check_cmd(cmd, args)
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/picosvg/svg_meta.py", line 67, in check_cmd
    raise ValueError(f"{cmd} has sets of {cmd_args} args, {len(args)} invalid")
ValueError: a has sets of 7 args, 6 invalid
[3/4] /Users/yisi/works/nanoemoji/tutorial-env/bin/python3 -m nanoemoji.write_fea codepointmap.csv > features.fea
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/Users/yisi/works/nanoemoji/tutorial-env/bin/nanoemoji", line 11, in <module>
    load_entry_point('nanoemoji', 'console_scripts', 'nanoemoji')()
  File "/Users/yisi/works/nanoemoji/src/nanoemoji/nanoemoji.py", line 375, in main
    app.run(_run)
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/yisi/works/nanoemoji/tutorial-env/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/yisi/works/nanoemoji/src/nanoemoji/nanoemoji.py", line 366, in _run
    subprocess.run(ninja_cmd, check=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-C', '/Users/yisi/works/nanoemoji/build']' returned non-zero exit status 1.
```

**Comment by yisibl** [comment]
I think it's a bug in svgo: https://github.com/svg/svgo/issues/1317

**Comment by yisibl** [comment]
In the [svg elliptical arc curve commands](https://www.w3.org/TR/SVG11/paths.html#PathDataEllipticalArcCommands), the white space after `large-arc-flag` and `sweep-flag` can be removed.

This is supported in the browser. What does picosvg use to resolve the path? Could the dependent upstream solve this problem?

**Comment by rsheeter** [comment]
We parse the path ourselves using an exceedingly basic parser.
