### ISSUE TITLE
picosvg fails on some noto examples

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/picosvg#236]
Failing to picosvg all of Noto blocks testing size implications nanoemoji refactoring (https://github.com/googlefonts/nanoemoji/pull/296) and new Paint formats.

```
picosvg ../color-fonts/font-srcs/noto-emoji/svg/emoji_u1f30d.svg

Traceback (most recent call last):
  File "nanoemoji/venv/bin/picosvg", line 11, in <module>
    load_entry_point('picosvg', 'console_scripts', 'picosvg')()
  File "picosvg/src/picosvg/picosvg.py", line 61, in main
    app.run(_run, argv=argv)
  File "nanoemoji/venv/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "nanoemoji/venv/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "picosvg/src/picosvg/picosvg.py", line 43, in _run
    svg = SVG.parse(input_file).topicosvg()
  File "picosvg/src/picosvg/svg.py", line 1193, in topicosvg
    svg.topicosvg(inplace=True)
  File "picosvg/src/picosvg/svg.py", line 1212, in topicosvg
    self.simplify(inplace=True)
  File "picosvg/src/picosvg/svg.py", line 666, in simplify
    self._simplify()
  File "picosvg/src/picosvg/svg.py", line 585, in _simplify
    to_process = reversed(tuple(c for c in self.breadth_first()))
  File "picosvg/src/picosvg/svg.py", line 585, in <genexpr>
    to_process = reversed(tuple(c for c in self.breadth_first()))
  File "picosvg/src/picosvg/svg.py", line 541, in breadth_first
    self._resolve_clip_path(child.attrib["clip-path"], transform),
  File "picosvg/src/picosvg/svg.py", line 482, in _resolve_clip_path
    clip_paths = [
  File "picosvg/src/picosvg/svg.py", line 483, in <listcomp>
    from_element(e).apply_transform(_element_transform(e, transform))
  File "picosvg/src/picosvg/svg.py", line 179, in from_element
    raise ValueError(f"Bad tag <{el.tag}>")
ValueError: Bad tag <{http://www.w3.org/2000/svg}g>
```

**Comment by anthrotype** [comment]
i'm trying to understand what the issue here is about, it's not clear from the title or the body of the issue.

IIUC this problem occurs while resolving clip-path attributes, and the clipPath element that is referenced contains a `<use>` element with some attributes (in the test case for #237, it has a `style="color:blue"`), and thus the `<use>` gets replaced with a `<g>` element with the same attributes, but then the `_resolve_clip_path` method assumes that clipPath element only contains shapes and not groups and from_element raises "Bad tag"..

Is that correct?

**Comment by rsheeter** [comment]
Yes.

**Comment by rsheeter** [comment]
Update to just generally cover restoration of function over all Noto assets. Found another interesting one to add a test for and fix: if `--clip_to_viewbox` is set we can be left with an empty group (` <g opacity="0.2"/>`) from emoji_u1f306.svg.
