### ISSUE TITLE
Error when removing comment in large SVG file with image

### ISSUE THREAD

**Issue by NightFurySL2001** [googlefonts/picosvg#297]
When parsing this svg file with `topicosvg`, an error occured:
[uni7cb9](https://github.com/googlefonts/picosvg/assets/33471049/d0655eaf-7683-4939-9988-b9cb0eaa3568)
```
Traceback (most recent call last):
  File "d:\Desktop\coding\svg2font\svgbuilder.py", line 209, in build_font_thread
    logs = build_font(
  File "d:\Desktop\coding\svg2font\newfontbuild.py", line 300, in build_font
    glyph, glyphadv = getOutlineFromSVG(svg_fulltext, metrics.upm, metrics.ascender, picoNormalize)
  File "d:\Desktop\coding\svg2font\newfontbuild.py", line 101, in getOutlineFromSVG
    picosvg.topicosvg(inplace=True, allow_text=True)
  File "D:\Desktop\coding\svg2font\kivy_venv\lib\site-packages\picosvg\svg.py", line 1352, in topicosvg
    self.remove_comments(inplace=True)
  File "D:\Desktop\coding\svg2font\kivy_venv\lib\site-packages\picosvg\svg.py", line 1023, in remove_comments
    el.getparent().remove(el)
AttributeError: 'NoneType' object has no attribute 'remove'
```

This seems to be due to the comment on the top of SVG:
`<!-- Generator: Adobe Illustrator 23.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->`

However, interestingly, when the image `xlink:href` and subsequent data is removed in SVG file, `topicosvg` is able to work correctly. 

Using this Python code to remove invalid element like the image that contains the `xlink:href` before parsing with `topicosvg` doesn't help:
```py
    picoerrors = picosvg.checkpicosvg()
    if picoerrors:
        for i in picoerrors:
            # skip if not image and style, prefilter
            if not re.search(r"/style\[\d+\]$", i) and not re.search(r"/image\[\d+\]$", i):
                continue

            # remove style and image elements
            for context in picosvg.breadth_first():
                if re.search(r"/style\[\d+\]$", context.path) or re.search(r"/image\[\d+\]$", context.path):
                    context.element.getparent().remove(context.element)
            break # only need remove once
    picosvg.topicosvg(inplace=True, allow_text=True)
```

**Comment by rsheeter** [comment]
Ty for reporting. Probably rather than trying to remove comments ourselves we should leverage `XMLParser(remove_comments=True)`, https://lxml.de/apidoc/lxml.etree.html#lxml.etree.XMLParser

**Comment by rsheeter** [comment]
^ might be wrong; when I add a comment above the root to a simple test file nothing breaks. If I run your file directly I get `Unable to convert to picosvg: BadElement: /svg[0]/style[0],BadElement: /svg[0]/image[0]`. If I manually delete those elements then picsvg succeeds.

**Comment by NightFurySL2001** [comment]
> If I run your file directly I get Unable to convert to picosvg: BadElement: /svg[0]/style[0],BadElement: /svg[0]/image[0].

I actually forgot to test this.... 😅 I do know BadElement should pop up in this scenario, but the given AttributeError caught me off hand.

After a bit more jiggling, I pinpoint the source of problem: `inplace=True` cause the AttributeError when removing comments.

Sample:
```py
from picosvg.svg import SVG
picosvg = SVG.parse("uni7cb9.svg")
print(picosvg.topicosvg(inplace=True).tostring())
```

**Comment by rsheeter** [comment]
>  https://github.com/NightFurySL2001/SVG2FontBuilder , which essentially expose picosvg to raw real world SVG inputs....)

Just in case you haven't seen it, https://github.com/googlefonts/nanoemoji does a somewhat similar job.

**Comment by NightFurySL2001** [comment]
To be honest, I have not been successful at making nanoemoji works. It either crashes or error out.

**Comment by anthrotype** [comment]
> inplace=True cause the AttributeError when removing comments.

@rsheeter did we also fix that?

**Comment by anthrotype** [comment]
> now gives ValueError as expected

there's the new drop_unsupported option to work around that as well ;)

**Comment by NightFurySL2001** [comment]
That is definitely a neat option too! 👍 Now I don't have to worry about rogue SVGs from users 😂
